language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
script: 
  - python tests/repo_test.py
  - cd tests
  - coverage run --source=pailab --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/* ./repo_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/* ./repo_disk_storage_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/* ./SQLiteJobRunner_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/* ./repo_git_handler_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/* ./tests/tutorial_test.py
  #- coverage run --source=pailab -a ./notebook_test.py
  #- coverage html --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/*
  - codecov
